# specify the log type here, valid values: http | access
type: http

# specify your account ID here (remove it if your log type is not "access")
cf_account_id: your_account_id_here

# specify your zone ID here (remove it if your log type is not "http")
cf_zone_id: your_zone_id_here

# specify your access token here. If you don't have one, generate one in Cloudflare Dashboard
cf_token: your_token_here

# specify the sampling rate for the logpull operation. Acceptable values: 0.01 to 1. By default, the value is 1. Only applicable for HTTP log type
rate: 0.5

# specify the logpull interval in seconds. By default, the tool will pull logs every 60 seconds.
interval: 30

# specify the niceness (priority) of the process from -20 to 19. Lower niceness value means higher priority.
nice: -10

# specify this option to true for debugging purposes.
debug: true

# configure different log destinations here as an array
log_dest:
    # you must specify all 5 options under this section, which includes name, path, prefix, no_organize and no_gzip.

    # give a unique name of the log destination configuration. Useful to identify in activity log.
  - name: first_dest
    # specify the folder path to store your logs. By default, logs will be stored in /var/log/cf_logs/.
    path: /var/log/first_path
    # specify the the log file name prefix. By default, the prefix would be 'cf_logs'.
    prefix: number_one
    # specify this option to true if you want to save the logs without organizing them into date and time folder.
    no_organize: false
    # specify this option to true if you want to save the logs in JSON format instead of compressed gzip format.
    no_gzip: true

    #you can configure more destinations here
  - name: second_dest
    path: /var/log/second_path
    prefix: number_two
    no_organize: true
    no_gzip: false

# Configure this to exclude certain fields from your logpull. Only applicable for HTTP log type.
# The following fields are available: BotScore,BotScoreSrc,CacheCacheStatus,CacheResponseBytes,CacheResponseStatus,CacheTieredFill,ClientASN,ClientCountry,ClientDeviceType,ClientIP,ClientIPClass,ClientRequestBytes,ClientRequestHost,ClientRequestMethod,ClientRequestPath,ClientRequestProtocol,ClientRequestReferer,ClientRequestURI,ClientRequestUserAgent,ClientSSLCipher,ClientSSLProtocol,ClientSrcPort,ClientXRequestedWith,EdgeColoCode,EdgeColoID,EdgeEndTimestamp,EdgePathingOp,EdgePathingSrc,EdgePathingStatus,EdgeRateLimitAction,EdgeRateLimitID,EdgeRequestHost,EdgeResponseBytes,EdgeResponseCompressionRatio,EdgeResponseContentType,EdgeResponseStatus,EdgeServerIP,EdgeStartTimestamp,FirewallMatchesActions,FirewallMatchesRuleIDs,FirewallMatchesSources,OriginIP,OriginResponseHTTPExpires,OriginResponseHTTPLastModified,OriginResponseStatus,OriginResponseTime,OriginSSLProtocol,ParentRayID,RayID,RequestHeaders,SecurityLevel,WAFAction,WAFProfile,WAFRuleID,WAFRuleMessage,WorkerCPUTime,WorkerStatus,WorkerSubrequest,WorkerSubrequestCount,ZoneID

fields.exclude:
  - ZoneID
