optional type: str
optional cf_account_id: str
optional cf_zone_id: str
optional cf_token: str
optional rate: float
optional interval: int
optional nice: int
optional debug: bool
type log_config:
  required name: str
  required path: str
  required prefix: str
  required no_organize: bool
  required no_gzip: bool
optional log_dest: list(type=log_config)
optional fields.exclude: list(type=str(equals=('BotScore','BotScoreSrc','CacheCacheStatus','CacheResponseBytes','CacheResponseStatus','CacheTieredFill','ClientASN','ClientCountry','ClientDeviceType','ClientIP','ClientIPClass','ClientRequestBytes','ClientRequestHost','ClientRequestMethod','ClientRequestPath','ClientRequestProtocol','ClientRequestReferer','ClientRequestURI','ClientRequestUserAgent','ClientSSLCipher','ClientSSLProtocol','ClientSrcPort','ClientXRequestedWith','EdgeColoCode','EdgeColoID','EdgeEndTimestamp','EdgePathingOp','EdgePathingSrc','EdgePathingStatus','EdgeRateLimitAction','EdgeRateLimitID','EdgeRequestHost','EdgeResponseBytes','EdgeResponseCompressionRatio','EdgeResponseContentType','EdgeResponseStatus','EdgeServerIP','EdgeStartTimestamp','FirewallMatchesActions','FirewallMatchesRuleIDs','FirewallMatchesSources','OriginIP','OriginResponseHTTPExpires','OriginResponseHTTPLastModified','OriginResponseStatus','OriginResponseTime','OriginSSLProtocol','ParentRayID','RayID','RequestHeaders','SecurityLevel','WAFAction','WAFProfile','WAFRuleID','WAFRuleMessage','WorkerCPUTime','WorkerStatus','WorkerSubrequest','WorkerSubrequestCount','ZoneID')))
